### ISSUE TITLE
Comments on first use of mobile app beta

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#29]
1. After signing in, on Content page, there are 3 options for downloading content and a Save button.
Can the selected option be changed later, how? Please add text explanation on the page.

2. "Applying Deltas" What does that mean? Not very informative to user.

3. "Downloading new, changed ..." Could you add a spinning wheel or progress bar or text "This could take a few minutes" ?

4. Went to Discussion. Sorting defaulted to Best rather than my usual setting of Newest

5. Main menu drop down. There is no explanation of Developer or Sync...

**Comment by brianrak** [comment]
Hello, @issekinichou. Thank you for the feedback!

1. Good point. This screen is still being designed. We'll add a note that the preferences can indeed be changed in the Preferences screen.

2. This was indeed primarily for us, just as a sanity check that the expected operations were being carried out. I realize this isn't particularly useful to the end user, but it at least indicates that something is going on. ("Applying deltas" means applying data changes received from the server, for example, as a result of making changes on the web site or via a different copy of the app.) The Git clients use similar terminology when they sync. I think I am going to say this one is okay. 

3. Good point. Will investigate.

4. I think this is probably happening because we are preventing third-party cookies from within the app. Since we are likely going to move away from Disqus, this might have to be postponed, but I will take a look.

5. Sorry about the confusion there. The entire "Developer" menu is for test purposes during the beta. We will be taking it out prior to release. 

Sync performs a sync. Do you feel that it would have been confusing if the Developer menu hadn't been there?

**Comment by issekinichou** [comment]
Re 5, developer menu.
No problem for me to ignore it now I know.
I suggest adding a sentence in the instructions to beta testers.

**Comment by brianrak** [comment]
An of build 0.913, the "Device Settings" page that you walk through on first run is now designed and contains a note explaining that the settings can be changed at any time in the Preferences page.

Regarding #3, for now I'm going to say that the text description is a sufficient indicator that the sync is in progress. We also provide a way to move the sync to the background as soon as the minimum required assets are downloaded.

Regarding #4, please open this as a separate bug.

Thank you!

**Comment by issekinichou** [comment]
Re #4, I just checked on the app and Announcements, Questions, Feedback, Bugs all open in Newest, as website.
Maybe it just happened on first launch?
I’ll need to experiment more by changing in browser on website and syncing the app.
