### ISSUE TITLE
Does the app (iOS) have an inactivity timeout?

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#48]
I was surprised when I launched the iOS app 0.913 this morning. It did not ask for password, but took me straight to the articles page. I opened and studied Review. I thought I signed out yesterday, over 12 hours earlier.
I suppose it is possible that I was still half asleep and actually did enter password (several taps inc. touch ID) on automatic pilot. 
Rather than leave it logged in to test reproducibility, could you say whether or not there is a timeout? If so, how long it is set to? And how about browser timeout? If you say there is one, and it is less than 12 hours, I would be willing to test it again, but I would prefer you test it your side, perhaps on a dummy account having no confidential information.

**Comment by brianrak** [comment]
Hello, @issekinichou. When you log in via either the browser or the mobile app, you should stay logged in for (I believe) two weeks, provided that you don't log out. Depending on your browser settings, the session is likely to be more durable on the mobile app because it doesn't depend on cookies, which are vulnerable to being wiped out due to various user actions within a regular browser. So it sounds like the behavior you experienced is correct.

**Comment by brianrak** [comment]
Update: the session expiration interval is now 60 days of non-use. This is the same for both the web app and the native app (but note that the sessions you create when you log into each of these are independent from one another -- one could expire while the other stays active).

This should ensure that, as long as you use the app/website occasionally, you should stay logged in.
