### ISSUE TITLE
Mobile app unusable unless signed in, which requires internet connection if currently signed out

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#56]
**Describe the bug**
If you sign out of the app, then it is totally unusable if you have no internet connection.

**To Reproduce**
Sign out
Disable internet connection
Launch app
Splash screen with sign in boxes.
Input password etc
Tap Sign in button
Error message
Error signing in: An error occurred while sending the request.

**Expected behavior**
Even without an internet connection, I would expect to be able to access the downloaded content on my device in just the same way an off-line dictionary or flashcard app. For example The Free Dictionary by Farlex has an offline mode provided you downloaded dictionaries in advance.

**Smartphone (please complete the following information):**
 iPod touch 6
iOS 11.4.1

**Additional context**
Is this behavior intentional? If so, then the instructions to users must be crystal clear. STAY SIGNED IN before you leave home. You cannot use this app if you are signed out, and you cannot sign in unless it can connect to the server via the internet.

I dislike this behavior. You should be able to bypass the sign in screen and access local downloaded content in an off-line mode. For example, to study downloaded articles. Is there some technical obstacle? I realize that changes will not be synced back to the server.

I have recently started testing the app without internet connection to simulate traveling. In practice I would only occasionally use it without internet access myself, but many user surely will. There should be a warning/reminder on sign out. 
Do you really want to sign out? You can stay signed in for 14 days before inactivity timeout. If you do sign out, you need an internet connection to sign in before you can use the app again.

So far I have found several areas related to sans-internet use that could be improved.

**Comment by brianrak** [comment]
Hello, @issekinichou. Thanks for the feedback. 

I can see we need to improve the messaging here.

Yes, you can use the app totally offline. But yes, you have to be signed in to use the app. The TL;DR version of the below is, just never sign out and you should be fine.

When you use the app, either offline or online, changes you make are aggregated and sync'd to the server. If you're offline, those changes are stored locally until you have a connection again.

This mechanism requires a signed-in user, because the changes have to be associated with a particular user.

Basically, once you sign in, you should just stay signed in. It doesn't cause any harm, and any time a background sync is performed as you use the app, your session is refreshed, so provided that you use the app regularly and sometimes have an internet connection, your session should never expire.

We recently changed the inactivity session expiration period to (I believe it was) 60 days to improve the user experience here. 

In 0.915 we also added a confirmation prompt when you sign out, which should help prevent accidental signouts.

Does this help to address your concerns?

**Comment by brianrak** [comment]
I improved the prompt that I describe above to be more clear about the fact that you can stay signed in and use the app offline, and that we recommend you stay signed in unless you need to switch to a different user account.

Closing for now.

**Comment by issekinichou** [comment]
1.01 sign out. Bang, out, no message. 
Will test more later.

**Comment by issekinichou** [comment]
Brian,

Build 101. 

iPad 4 mini iOS 11.4.1.
Menu, Sign out.
Straight to orange splash screen, Welcome, Sign in.
No confirmation prompt, no message, no warning, nothing has changed.
Ok?


iPod touch 6 iOS 11.4.1
Ditto

Let me know if you want me to do any more tomorrow.
Out of time tonight.

Richard

**Comment by brianrak** [comment]
You are absolutely right. We lost this when I integrated a different change. Will fix pronto. Please look for Release Candidate 3 forthwith!

**Comment by issekinichou** [comment]
Forthwith? Eh, where is it? Github releases = 0. Testflight nothing new.

**Comment by issekinichou** [comment]
Re the message displayed in offline mode if doing something that requires internet connection.
Eg. Disable wifi, Review a couple of cards, Force Sync.
"Proceeding in offline mode"

Could you increase the time for which this message is displayed? It disappears before you get a chance to read it unless you know it's coming and pay attention.

**Comment by brianrak** [comment]
Forthwith took a little longer than anticipated. The build is submitted and should show up any moment now.

Regarding the offline mode message, is it really that important? We're sort of trying to speed through that whole screen as quickly as possible. Basically, if you're not connected, and that screen works, you can assume that the app is working properly in offline mode.

**Comment by issekinichou** [comment]
You are right. It is not really important. Sorry to bother you with that suggestion.

**Comment by brianrak** [comment]
No problem. We appreciate all your hard work on the beta!
