### ISSUE TITLE
Some comments on app operation in offline and online modes

### ISSUE THREAD

**Issue by issekinichou** [brianrak/satori-reader-mobile-beta#61]
I have been testing the app on my iPod in offline mode (internet disconnected) to simulate traveling away from home. It is rather hard to test review because it involves waiting to see the results, so that's probably finished now.
Mostly it works fine, though some messages could be improved (see issues 57 and 60)

In particular, I was wondering how sync works. I have discovered the following. I expect most of this is obvious and known to you, but there might be something of interest here.

With a wifi internet connection, the app automatically syncs. 
For example, during a review, the numbers on the web site change. You have to exit and reopen the review page to refresh the display.
I hope this will be explained to users. I wonder if the menu item 'Synchronize' should be more explicit as it implies no sync occurs unless you invoke it. How about 'Forced sync'? I thought you might be able to prevent a sync from happening (card deletion by accident etc) by not using it. Also I was invoking this sync unnecessarily to ensure changes were passed on when I had the web site open simultaneously.

On iPod, I signed in, disabled wifi for two days and read an article and added study cards.
On iPad, I maintained wifi, read the same article and added some of the same cards. Did a review the next day. Noted down the words, Grades, and day numbers. Noted the Review summary eg 8/15/2083 (8 cards due, 15 marked hard, all cards 2083). Compared numbers on iPad app and web site.
On iPod, I did an offline review, gave some different answers to cards that had been added to both devices, and compared summary numbers. Then enabled wifi.
Without me selecting the sync menu item, the iPod immediately synced with the server, as indicated by the review summary numbers. It seems to have done an intelligent merge (not a replacement of one by the other), although I may update this report in a few days after the results emerge from future reviews. For example if the same card was marked hard and easy on different devices, which takes priority (difficulty or chronology?). Ditto card deletion: is it deleted or retained?

Another merge was Dashboard Started, which added to the server's list articles started on offline iPod. Probably best, although I had deliberately changed two to unread to clear up the list.

**Comment by brianrak** [comment]
Hello, @issekinichou. Thanks for the feedback. I can see that it would be helpful to change some menu items and/or explain how sync works a little more clearly.

When an internet connection is available, the app continuously attempts to synchronize changes,  basically as they occur. The app knows when changes have occurred and doesn't attempt to sync if no changes have been made. At longer intervals (I believe it's 1 hour), it syncs even if no changes have been made locally, to bring down any changes from other instances of the app or use of the website.

Every time you start the app, the app tries to perform a sync to make sure all of the data it needs is fresh and up-to-date. Why not just always do background syncs? This step is necessary primarily because there are some data states in which it is not possible to use the app at all, and this step ensures that everything is as it needs to be. Once into such a copacetic state, the background sync should be enough to keep everything all sync'd up.

So, to answer your question, there should be no reason usually to manually invoke the Synchronize screen. The exception would be if you make a change on a different device and you want to force a sync instead of waiting for it to happen automatically.

Regarding changes to the same data from different devices, we do indeed try our best to merge that data intelligently, and the way the data is merged depends on the type of data. Review card results are interleaved -- you get credit for both. Certain other data is applied using a "most recent wins" tie-breaking rule.

I will see about changing the terminology in the menu items.

**Comment by brianrak** [comment]
In 0.915, we have removed "Synchronize" from the main menu because it's not really a button you need to regularly use. We've added a section within the Account screen that explains how the synchronization works and gives you a button to force synchronization. In our fix for #60, we also improved the messages shown during synchronization in offline mode, so hopefully this alleviates a lot of the confusion. Thank you for the feedback and suggestions!
